### ISSUE TITLE
use Raxx.View

### ISSUE THREAD

**Issue by CrowdHailer** [CrowdHailer/watercooler#1]
I use this as my example implementation, it would be helpful to be up to date

**Comment by CrowdHailer** [comment]
This would also enable removing phoenix_html as a dependency

**Comment by wayann** [comment]
hopefully this will close the issue:
https://github.com/CrowdHailer/watercooler/pull/5

**Comment by CrowdHailer** [comment]
Yep perfect, can close this now.
